CREATE TABLE `tblUsuarios` (
`strIdEmpresa` varchar(44),
`strIdUsuario` varchar(44),
`strApellido1` varchar(36),
`strApellido2` varchar(32),
`strNombres` varchar(260),
`strAFP` varchar(116),
`strEPS` varchar(44),
`strARP` varchar(32),
`strCCF` varchar(40),
`strClave` varchar(16),
`intSalarioBase` varchar(28),
`intValorAPagar` varchar(24),
`intDiaLimitePago` varchar(4),
`strOperador` varchar(64),
`intTelefono` varchar(0)
);

INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70288616','C70288616','HENAO','QUINTERO','ADRIAN ALONSO','PROTECCIÓN (ING + PROTECCIÓN)','NUEVA EPS','POSITIVA','COMFAMA','','689455','234000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041327191','C1041327191','CASTAÑO','SANCHEZ','ALBEIRO DE JESUS','PROTECCIÓN (ING + PROTECCIÓN)','NUEVA EPS','COLMENA','','7404','689455','250000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70290095','C70290095','CARDONA','ACEVEDO','ALBERT NEDY','PROTECCIÓN (ING + PROTECCIÓN)','EPS SURA','COLMENA','','7981','689455','203000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70286069','C70286069','JARAMILLO','GALLEGO','ALBERTO DE JESUS','PROTECCIÓN (ING + PROTECCIÓN)','SAVIA SALUD','SURA','','4992','800000','261000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70288204','C70288204','CEBALLOS','FRANCO','ALVEIRO DE JESUS','','SAVIA SALUD','','','7519','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43420436','C43420436','LÓPEZ','SÁNCHEZ','ANA  LIBIA','PROTECCION','SALUDCOOP','','','0436','800000','240000','0','PAGO SIMPLE','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1007316299','C1007316299','ARANGO','GARCIA','ANDRES EDUARDO','PORVENIR','SAVIA SALUD','POSITIVA','COMFAMA','','689455','190000','0','GETEM','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43857142','C43857142','SANTA','HENAO','ARELIS JOHANA','PROTECCIÓN (ING + PROTECCIÓN)','EPS SURA','COLMENA','','5823','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('N811047081','C736947','','','ASOCIACIÓN DE SUSCRIPTORES DEL ACUEDUCTO LA MINA VEREDA LA ENEA','','','','','0807','689455','289000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('N811042464','C70285043','','','ASOCIACIÓN DE USUARIOS ACUEDUCTO MULTIVEREDAL PIEDRAGORDA','PROTECCIÓN (ING + PROTECCIÓN)','COMFENALCO','POSITIVA','COMFENALCO','','1379000','468000','0','GETEM','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('N811043821','C43421761','','','ASOCIACIÓN DE USUARIOS DEL ACUEDUCTO MULTIVEREDAL SAN JOSE CANTOR','','','','','1104','689455','271000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041324495','C1041324495','GOMEZ','HENAO','AURA CRISTINA','PROTECCIÓN (ING + PROTECCIÓN)','SALUDCOOP','','','7816','689455','212000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43419242','C43419242','QUINTERO','LOPEZ','BEATRIZ ELENA','COLPENSIONES ISS PENSIONES','COMFENALCO','','','9023','1072000','316000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43421019','C43421019','ARIAS','SANCHEZ','BLANCA MERY DE LA TRINIDAD','COLFONDOS','COMFENALCO','SURA','','2088','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041327681','C1041327681','CASTAÑO','VERGARA','CAMILO ALEXANDER','PROTECCIÓN (ING + PROTECCIÓN)','SAVIA SALUD','','','2283','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70290167','C70290167','ALZATE','GIRALDO','CARLOS ANDRES','PROTECCIÓN (ING + PROTECCIÓN)','COMFENALCO','','','956','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70290481','C70290481','PUERTA','GIL','CARLOS ANDRES','','','','','2570','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70290720','C70290720','CARDONA','SANCHEZ','CARLOS MARIO','PROTECCIÓN (ING + PROTECCIÓN)','COOMEVA','COLMENA','','5527','700000','230000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70290180','C70290180','GIRALDO','GIRALDO','CESAR AUGUSTO','PORVENIR','EPS SURA','','','2416','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041325580','C1041325580','ORREGO','GIRALDO','CLAUDIA ANDREA','PORVENIR','SAVIA SALUD','COLMENA','','602','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041328232','C1041328232','LOPEZ','CASTAÑO','DANIEL','PORVENIR','CAFESALUD','','','4537','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041327991','C1041327991','SANTA','ACEVEDO','DANIELA','PORVENIR','SALUDCOOP','POSITIVA','COMFAMA','','689455','190000','0','GETEM','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041327932','C1041327932','ISAZA','CARDONA','DANIELA ANDREA','PORVENIR','NUEVA EPS','COLMENA','','9505','720000','226000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041325628','C1041325628','ALZATE','GIL','DANILO ADOLFO','COLPENSIONES ISS PENSIONES','COOMEVA','SURA','','818','689455','195000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C22050745','C22050745','MURILLO','DE ARBELAEZ','DEBORA LUZ','','SALUDCOOP','','','3612','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43420376','C43420376','FRANCO','ZAPATA','DORIS EUGENIA','COLFONDOS','CAFESALUD','COLMENA','','9338','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43420605','C43420605','ECHEVERRY','ATEHORTUA','ELDA PATRICIA','PROTECCIÓN (ING + PROTECCIÓN)','SALUDCOOP','SURA','','8404','689455','204000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041325064','C1041325064','GALLO','GUTIERREZ','ELIZABETH CRISTINA','PORVENIR','SAVIA SALUD','SURA','','5918','689455','212000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70287627','C70287627','ZAPATA','ZAPATA','ELKIN URIEL','','','','','9310','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70286410','C70286410','SANTA','MARIN','EVER SAUL','','SALUDCOOP','','','es2312','689455','100000','0','NUEVO SOI','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041328194','C1041328194','FRANCO','CARDONA','EVERLEY ALEXIS','PROTECCIÓN (ING + PROTECCIÓN)','SALUDCOOP','','','6134','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70288492','C70288492','QUINTERO','SERNA','FABIO DE JESUS','COLPENSIONES ISS PENSIONES','COMFENALCO','POSITIVA','COMFAMA','','689455','234000','0','FUNDASOCIAL','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43421643','C43421643','MONSALVE','ARBELAEZ','FANNY AMPARO','','SALUDCOOP','','','8141','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041325459','C1041325459','MENDOZA','MENA','FELIX JAIR','PORVENIR','COMFENALCO','COLMENA','COMFENALCO','6006','689455','216000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041326882','C1041326882','VALENCIA','HENAO','FERNEY DE JESUS','HORIZONTE','COMFENALCO','','','6496','689455','212000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43420783','C43420783','SÁNCHEZ','HENAO','FLOR MARGARITA','PROTECCIÓN (ING + PROTECCIÓN)','COMFENALCO','POSITIVA','','8260','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C3354316','C3354316','SANTA','MONTOYA','GERMAN DE JESUS','PROTECCIÓN (ING + PROTECCIÓN)','CAFESALUD','POSITIVA','COMFAMA','','689455','234000','0','GETEM','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C3596025','C3596025','RIVERA','MARIN','GILBERTO DE JESUS','','SAVIA SALUD','','','4185','1011000','141000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43421574','C43421574','MARIN','ARBELAEZ','GLADYS YANETH','PORVENIR','SALUDCOOP','POSITIVA','COMFAMA','','689455','190000','0','GETEM','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C22052255','C22052255','QUINTERO','CARDONA','GLORIA  INES','COLFONDOS','SALUDCOOP','COLMENA','','1312','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43420102','C43420102','ARIAS','MARIN','GLORIA ELENA','PROTECCIÓN (ING + PROTECCIÓN)','COMFENALCO','SURA','','9260','689455','194000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70286900','C70286900','ALZATE','CASTAÑO','GUILLERMO LEON','COLPENSIONES','NUEVA EPS','','','7424','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70287551','C70287551','ARBELAEZ','ARBELAEZ','GUSTAVO ANTONIO','COLPENSIONES ISS PENSIONES','SALUDCOOP','ARP SURA','','6704','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041324999','C1041324999','MARTINEZ','LOPEZ','HECTOR DARIO','COLPENSIONES ISS PENSIONES','EPS SANITAS','','','7701','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70286678','C70286678','MORALES','CASTRILLON','HECTOR DARIO','','SALUDCOOP','','','8707','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70326619','C70326619','RIVERA','MONSALVE','HECTOR JAIME','COLPENSIONES ISS PENSIONES','COMFENALCO','POSITIVA','','','689455','203000','0','GETEM','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041327834','C1041327834','BUSTAMANTE','AGUDELO','HENRY ALEXANDER','','COMFENALCO','POSITIVA','COMFAMA','','689455','203000','0','GETEM','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1040037467','C1040037467','ALZATE','SANTA','HENRY ALONSO','HORIZONTE','COMFENALCO','','','ha7128','689455','210000','0','NUEVO SOI','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C22052218','C22052218','CARDONA','DUQUE','HERMILDA','PROTECCIÓN (ING + PROTECCIÓN)','SAVIA SALUD','','','1412','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70290465','C70290465','CARDONA','MARIN','HERNAN ARLEY','PORVENIR','EPS SURA','POSITIVA','COMFAMA','','689455','234000','0','GETEM','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041324106','C1041324106','GARCIA','RIVERA','HERNEY DE JESUS','PORVENIR','SALUDCOOP','COLMENA','','8073','689455','212000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70285320','C70285320','MARIN','LOPEZ','HUMBERTO DE JESUS','','COMFENALCO','','','hj7252','689455','100000','0','NUEVO SOI','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43855851','C43855851','HENAO','ZAPATA','JENNY ANDREA','PROTECCIÓN (ING + PROTECCIÓN)','SALUDCOOP','POSITIVA','','1223','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43857114','C43857114','SANTA','PULIDO','JHENNY VIVIANA','PROTECCIÓN (ING + PROTECCIÓN)','COMFENALCO','','','2452','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041325263','C1041325263','VERGARA','CASTAÑO','JOHANY ALEJANDRO','PORVENIR','COOMEVA','POSITIVA','','4828','689455','219000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70289633','C70289633','MARIN','GALLO','JOHN FABER','PROTECCIÓN (ING + PROTECCIÓN)','SALUDCOOP','POSITIVA','','6250','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70288344','C70288344','MUÑOZ','VALENCIA','JOHN JAIRO','COLPENSIONES ISS PENSIONES','COMFENALCO','','','2030','689455','209000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041324906','C1041324906','ORREGO','LOPEZ','JONATHAN DEYRSON','COLPENSIONES','SALUDTOTAL','SURA','','3133','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70290086','C70290086','GALEANO','HENAO','JOSE ARLEY','COLFONDOS','NUEVA EPS','COLMENA','','3282','689484','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70287369','C70287369','SANTA','MONTOYA','JOSE ARNULFO','PROTECCIÓN (ING + PROTECCIÓN)','SALUDCOOP','POSITIVA','COMFAMA','','689455','234000','0','GETEM','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C736786','C736786','GIRALDO','AGUDELO','JOSE HERMOGENES','','NUEVA EPS','','','5631','689455','81000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C3594541','C3594541','QUINTERO','SALAZAR','JOSE JESUS','','SALUDCOOP','','','9973','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70289858','C70289858','HERRERA','PULGARIN','JOSE LEONEL','PORVENIR','COMFENALCO','POSITIVA','COMFAMA','','689455','234000','0','FUNDASOCIAL','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C7521662','C7521662','MARTINEZ','CARDONA','JOSE WILLIAM Y ADICIONAL','COLPENSIONES ISS PENSIONES','SALUDCOOP','','','9262','689455','248000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041326182','C1041326182','MARIN','VASCO','JUAN CARLOS','PROTECCIÓN (ING + PROTECCIÓN)','NUEVA EPS','POSITIVA','COMFAMA','','689455','234000','0','GETEM','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70288280','C70288280','ISAZA','JARAMILLO','JUAN CARLOS','PROTECCIÓN (ING + PROTECCIÓN)','COMFENALCO','SURA','','7428','720000','221000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041324545','C1041324545','HENAO','MORALES','JUAN DAVID','PORVENIR','SAVIA SALUD','COLMENA','','5045','720000','228000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70290832','C70290832','RIVERA','ZULUAGA','JUAN FELIPE','PORVENIR','COMFENALCO','COLMENA','COMFENALCO','2343','1126000','383000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70289444','C70289444','ALZATE','GIRALDO','JUAN FERNANDO','HORIZONTE','COOMEVA','','','5023','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70289614','C70289614','CEBALLOS','RIVERA','JUAN FERNANDO','PORVENIR','SAVIA SALUD','COLMENA','','2672','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('N900042041','C70286165','','','JUNTA DE ACCIÓN COMUNAL VEREDA ALTO DE LA COMPAÑÍA','','','','','1538','898700','492000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70286525','C70286525','ORREGO','MENESES','JUVENAL ANTONIO','PROTECCIÓN (ING + PROTECCIÓN)','COMFENALCO','','','4601','720000','250000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43856879','C43856879','VERGARA','HENAO','LEIDY CRISTINA','HORIZONTE','SALUDCOOP','','','8087','689455','212000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041326701','C1041326701','BOTERO','AGUDELO','LEIDY JOHANA','PORVENIR','COMFENALCO','','','3983','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C75038684','C75038684','ROLDAN','RESTREPO','LEONARDO','HORIZONTE','SALUDCOOP','POSITIVA','COMFAMA','','689455','234000','0','GETEM','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43856598','C43856598','GALLO','VALENCIA','LILLIANA MARIA','','SALUDCOOP','','','7319','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041325421','C1041325421','RIVERA','ZULUAGA','LINA MARIA','PROTECCIÓN (ING + PROTECCIÓN)','COMFENALCO','SURA','','2534','1480000','442000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041326346','C1041326346','MARIN','MORALES','LISANDRO ADOLFO','HORIZONTE','SALUDCOOP','COLMENA','','868','0','227000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70286969','C70286969','MARIN','VERGARA','LUIS ALBEIRO','COLPENSIONES','NUEVA EPS','','','3884','689455','','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70286654','C70286654','CASTRILLON','CASTAÑO','LUIS ALBERTO','','','','','5956','','335000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70289062','C70289062','OSPINA','FRANCO','LUIS CARLOS','PROTECCIÓN (ING + PROTECCIÓN)','COOMEVA','','','2601','598400','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70285118','C70285118','GIRALDO','GIRALDO','LUIS EDUARDO','','SALUDCOOP','','','3671','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C3596206','C3596206','CARDONA','CASTAÑO','LUIS EFREN','COLPENSIONES ISS PENSIONES','COMFENALCO','POSITIVA','','6026','6443500','1906000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C3594677','C3594677','GIRALDO','BOTERO','LUIS HORACIO','','SALUDCOOP','','','lh0499','689455','100000','0','NUEVO SOI','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041325941','C1041325941','PETRO','QUINTERO','LUISA FERNANDA','PROTECCIÓN (ING + PROTECCIÓN)','NUEVA EPS','COLMENA','','2583','689455','217000','0','ENALCE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041328029','C1041328029','LOPEZ','ALZATE','LUISA FERNANDA','HORIZONTE','COMFENALCO','COLMENA','','1718','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43420471','C43420471','GUTIERREZ','MARIN','LUZ MARINA','PROTECCIÓN (ING + PROTECCIÓN)','COMFENALCO','SURA','','5241','689455','195000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C22049815','C22049815','MURILLO','MARIN','MARGARITA INES','','NUEVA EPS','','','42','689455','87000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C44002177','C44002177','CARDEÑO','ALZATE','MARGARITA MARIA','COMFENALCO','HORIZONTE','ARP SURA','','2196','689455','212000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041325018','C1041325018','MARIN','HENAO','MARIA ANDREA','PORVENIR','COMFENALCO','SURA','','1491','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C22051495','C22051495','QUINTERO','QUINTERO','MARIA CONSUELO','','SALUDCOOP','','','6330','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43419265','C43419265','ALVAREZ','MARIN','MARIA EUGENIA','','SUSALUD','','','6169','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C21387422','C21387422','FONNEGRA','VELEZ','MARIA INES GABRIELA','','COMFENALCO','','','8908','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43419547','C43419547','CASTAÑO','QUICENO','MARIA MARGARITA','PROTECCIÓN (ING + PROTECCIÓN)','SALUDCOOP','COLMENA','COMFAMA','mm4147','689455','212000','0','NUEVO SOI','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43118093','C43118093','TABARES','GIRALDO','MARIA ROSALBA','PROTECCIÓN (ING + PROTECCIÓN)','EPS SURA','COLMENA','','2018','1148000','347000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43420197','C43420197','AGUDELO','CARVAJAL','MARIELA ','PORVENIR','COMFENALCO','','','4409','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C22048232','C22048232','ECHEVERRY','DE GIL','MARTA ROSA','','COMFENALCO','','','2715','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43420467','C43420467','CASTAÑO','FRANCO','MARTHA ELENA','PORVENIR','EPS SURA','','','469','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43419202','C43419202','JARAMILLO','GALLEGO','MARTHA LUZ','PROTECCIÓN (ING + PROTECCIÓN)','EPS SURA','SURA','','6350','689455','203000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1041328107','C1041328107','MARIN','MARIN','MAURICIO','PORVENIR','NUEVA EPS','','','1613','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70290651','C70290651','GIL','CEBALLOS','MAURICIO HERNEY','PROTECCIÓN (ING + PROTECCIÓN)','COOMEVA','','','2778','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C1060268581','C1060268581','MEJIA','HENAO','MIGUEL ANGEL','','NUEVA EPS','','','1780','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43420364','C43420364','CASTAÑO','AGUDELO','MIRIAM DEL SOCORRO','','EPS SURA','','','5994','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C3594770','C3594770','OSPINA','ACEVEDO','MOISES NOE','','SURA','','','5470','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43420514','C43420514','VERGARA','CASTAÑO','MONICA LUCIA','COLPENSIONES ISS PENSIONES','COMFENALCO','','','9782','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43448590','C43448590','PEÑA','HERNANDEZ','MONICA MARIA','HORIZONTE','EPS SANITAS','','','1021','720000','223000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43902352','C43902352','VILLA','NAVAS','MONICA PATRICIA','PORVENIR','COMFENALCO','COLMENA','','9327','689455','217000','0','ENLACE OPERATIVO','3136299651');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43856572','C43856572','MARIN','SANCHEZ','NANCY DE LA TRINIDAD','PORVENIR','NUEVA EPS','POSITIVA','COMFAMA','','689455','234000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70286362','C70286362','LOPEZ','','NIVARDO DE JESUS','PORVENIR','SALUDTOTAL','COLMENA','','3342','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C22052196','C22052196','GALLO','ALZATE','NORA CECILIA','','COMFENALCO','','','2574','689455','100000','0','PAGO SIMPLE','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C43856917','C43856917','CASTRILLON ','CEBALLOS','NORA MARLENY','PROTECCIÓN (ING + PROTECCIÓN)','SALUDCOOP','','','1815','880000','274000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('N3596206','C3596206','','','NOTARIA UNICA SAN VICENTE','','','','','6026','1760000','437000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70289120','C70289120','TORRES','SANCHEZ','OMAR DE JESUS','PORVENIR','SALUDCOOP','','','4107','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70069939','C70069939','ZAPATA','','ORLANDO DE JESUS','','SALUDCOOP','','','5185','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70287712','C70287712','CARVAJAL','','OSCAR ALONSO','COLPENSIONES','SAVIA SALUD','POSITIVA','COMFAMA','','689455','234000','0','GETEM','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70289924','C70289924','MARIN','ECHEVERRY','OSCAR FERNAN','PORVENIR','EPS SURA','COLMENA','','7183','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C71664826','C71664826','GIL','CASTRILLON','OTONIEL DE JESUS','PROTECCIÓN (ING + PROTECCIÓN)','SALUDCOOP','SURA','','1055','689455','203000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70290680','C70290680','MORALES','MARIN','RAMON ALBERTO','PORVENIR','SALUDCOOP','COLMENA','','1756','689455','217000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C70289279','C70289279','AGUDELO','GIL','RAMON OCTAVIO','PORVENIR','EPS SURA','','','1201','689455','210000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`,`intTelefono`) VALUES('C3595891','C3595891','GALLO','GALLEGO','REINALDO DE JESUS','','COMFENALCO','','','641','689455','100000','0','ENLACE OPERATIVO','');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C22050508','C22050508','JARAMILLO','ZULUAGA','ROSA INES','COLPENSIONES ISS PENSIONES','COMFENALCO','','','8311','689455','100000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C22052109','C22052109','GIRALDO','MONSALVE','ROSALBA ','PORVENIR','COMFENALCO','SURA','','3494','689455','217000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C43856880','C43856880','QUINTERO','VERGARA','ROSIBEL VIVIANA','ISS','COMFENALCO','','','1786','689455','217000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C70286894','C70286894','DUQUE','SALAZAR','RUBEN DARIO','PORVENIR','SAVIA SALUD','POSITIVA','COMFAMA','','689455','234000','0','GETEM');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C43421994','C43421994','HENAO','HENAO','SANDRA DEL SOCORRO','PORVENIR','SALUDCOOP','SURA','','ss5413','689455','217000','0','NUEVO SOI');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C32243446','C32243446','LOPEZ','CASTAÑO','SANDRA MILENA','PROTECCIÓN (ING + PROTECCIÓN)','COMFENALCO','','','1619','689455','210000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C43855537','C43855537','SANCHEZ','LOPEZ','SANDRA YANETH','','','','','','689455','190000','0','GETEM');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C1041326230','C1041326230','HERNANDEZ','ARBELAEZ','SEBASTIAN CAMILO','PORVENIR','EPS SURA','COLMENA','COMFAMA','7500','689455','212000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C70289147','C70289147','MUÑOZ','SANTA','SNEYTHER ARMANDO','PROTECCIÓN (ING + PROTECCIÓN)','CRUZ BLANCA','COLMENA','','2422','800000','249000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C15365798','C15365798','QUINTERO','CARDONA','TEODARDO DE JESUS Y ADICIONAL','COLPENSIONES ISS PENSIONES','COMFENALCO','','','5678','689455','252000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C43856108','C43856108','GOMEZ','DUQUE','TERESA DE JESUS','HORIZONTE','SALUDCOOP','','','2692','1672000','532000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C22050904','C22050904','ALZATE','FRANCO','TRINIDAD DEL SOCORRO','','NUEVA EPS','','','1822','689455','86000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C70289308','C70289308','GIRALDO','SANCHEZ','URIEL ANTONIO','HORIZONTE','COMFENALCO','COLMENA','','8015','689455','100000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C70288534','C70288534','SANTA','CARDONA','VICTOR ARBEY','','SALUDCOOP','','','3588','689455','100000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C70290236','C70290236','ALZATE','GIL','VICTOR JULIO','COLPENSIONES ISS PENSIONES','EPS SURA','COLMENA','COMFAMA','6086','689455','232000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C70287564','C70287564','VERGARA','HENAO','WILLIAM ALBERTO','HORIZONTE','COMFENALCO','','','5547','674000','221000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C70289660','C70289660','CARDONA','QUINTERO','WILLIAM ANTONIO','COLPENSIONES ISS PENSIONES','SALUDCOOP','','','5976','689455','234000','0','GETEM');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C70290955','C70290955','CASTAÑO','FRANCO','WILLMAN ALEXANDER','HORIZONTE','COMFENALCO','COLMENA','COMFAMA','3416','689455','225000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C39452754','C39452754','ZAPATA','MARIN','YEIDY LUBENY','PROTECCIÓN (ING + PROTECCIÓN)','NUEVA EPS','COLMENA','','947','689455','217000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C1038212219','C1038212219','GALLEGO','HENAO','YIDI YASMIN','PROTECCIÓN (ING + PROTECCIÓN)','SALUDCOOP','SURA','','8301','689455','217000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C1036945287','C1036945287','CARDONA','SANCHEZ','YOVANY ARLEY','HORIZONTE','SALUDCOOP','POSITIVA','COMFAMA','','689455','234000','0','GETEM');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C40784909','C40784909','CASTRO','HURTADO','YUBELY','COLPENSIONES ISS PENSIONES','SALUDCOOP','COLMENA','','9356','689455','212000','0','ENLACE OPERATIVO');
INSERT INTO `tblUsuarios` (`strIdEmpresa`,`strIdUsuario`,`strApellido1`,`strApellido2`,`strNombres`,`strAFP`,`strEPS`,`strARP`,`strCCF`,`strClave`,`intSalarioBase`,`intValorAPagar`,`intDiaLimitePago`,`strOperador`) VALUES('C42135989','C42135989','RUIZ','SANCHEZ','YUDIT LIZED','PORVENIR','EPS SURA','COLMENA','','7610','689455','304000','0','ENLACE OPERATIVO');
